/**
 * Terminal client copy: one English dictionary keyed by the same locale keys
 * the shared presenters return, plus the terminal's own prompts and messages.
 * @module @deepseek-ai/dsh-terminal-views/copy
 */
import type { ApprovalChoiceKey, ApprovalNeedKey } from '@deepseek-ai/dsh-presentation-approval'
import type { ToolTitleKey } from '@deepseek-ai/dsh-presentation-tool-call'
import { PANEL_COPY } from './copy-panels.ts'

/** Title of every tool row, one entry per {@link ToolTitleKey}. */
const TOOL_TITLES = {
  'todo.rowTitle': 'Update to-do list',
  'ask.rowTitle': 'Ask question',
  'tool.title.search': 'Search',
  'tool.title.read': 'Read',
  'tool.title.bash': 'Bash',
  'tool.title.write': 'Write',
  'tool.title.edit': 'Edit',
  'tool.title.code': 'Code',
  'tool.title.generic': 'Tool call',
  'tool.title.inspect': 'Query Cordis environment',
  'tool.title.runCordis': 'Run Cordis Plugin',
  'tool.title.stopCordis': 'Stop Cordis Plugin',
  'tool.title.removeCordis': 'Remove Cordis Plugin',
  'tool.title.pwsh': 'Pwsh',
  'tool.title.readImage': 'Read image',
  'tool.title.createGoal': 'Create goal',
  'tool.title.getGoal': 'View goal',
  'tool.title.updateGoal': 'Update goal',
  'tool.title.createSchedule': 'Create reminder',
  'tool.title.listSchedules': 'List reminders',
  'tool.title.deleteSchedule': 'Delete reminder',
  'tool.title.updateSchedule': 'Update reminder',
  'tool.title.inspectProviders': 'Inspect providers',
  'tool.title.queryRuntime': 'Query runtime',
  'tool.title.inspectPlugins': 'Inspect plugins',
  'tool.title.workflow': 'Run workflow',
  'tool.title.ralph': 'Run ralph loop',
  'tool.title.readEvent': 'Read event',
  'tool.title.searchEvents': 'Search events',
  'tool.title.traceEvent': 'Trace event',
  'tool.title.searchSessions': 'Search sessions',
  'tool.title.traceSession': 'Trace session',
  'tool.title.listModels': 'List models',
  'tool.title.subagent': 'Create subagent',
  'tool.title.listAgents': 'List subagents',
  'tool.title.sendMessage': 'Send message',
  'tool.title.interruptAgent': 'Interrupt agent',
  'tool.title.listJobs': 'List background jobs',
  'tool.title.readJob': 'Read job output',
  'tool.title.killJob': 'Cancel background job',
  'tool.title.openTerminal': 'Open terminal',
  'tool.title.readTerminal': 'Read terminal',
  'tool.title.listTerminals': 'List terminals',
  'tool.title.signalTerminal': 'Signal terminal',
  'tool.title.closeTerminal': 'Close terminal',
  'tool.title.lsp': 'Query code symbols',
  'tool.title.spawnTeammate': 'Create teammate',
  'tool.title.createTeamTask': 'Create team task',
  'tool.title.getTeamTask': 'Read team task',
  'tool.title.updateTeamTask': 'Update team task',
  'tool.title.listTeamTasks': 'List team tasks',
  'tool.title.waitAgent': 'Wait for subagent',
} as const satisfies Record<ToolTitleKey, string>

/** Sentence completing "I need permission to …", one per {@link ApprovalNeedKey}. */
const NEEDS = {
  'need.shell': 'I need permission to run a command',
  'need.edit': 'I need permission to change files in your project',
  'need.read': 'I need permission to read your files or a web page',
  'need.search': 'I need permission to search your project or the web',
  'need.code': 'I need permission to run a program',
  'need.generic': 'I need permission to take an action',
} as const satisfies Record<ApprovalNeedKey, string>

/** The three decisions, one per {@link ApprovalChoiceKey}. */
const CHOICES = {
  allowOnce: 'Allow once',
  allowSession: 'Allow for this session',
  reject: 'Reject',
} as const satisfies Record<ApprovalChoiceKey, string>

/** Lines of the approval prompt around its sentence and decisions. */
const APPROVAL = {
  because: 'Because: {reason}',
  'technical.tool': 'Tool: {toolName}',
  'technical.call': 'Call: {callId}',
  'approval.keys': 'y allow once · s allow for this session · n reject',
} as const

/** Messages owned by the terminal client itself. */
const TERMINAL = {
  'composer.placeholder': 'Message the agent, or type / for commands',
  'composer.hint': 'Enter sends · Alt+Enter or \\ then Enter adds a line · /help lists commands',
  'status.working': 'Working… Ctrl+C stops the turn',
  'status.cancelling': 'Stopping…',
  'turn.interrupted': 'Interrupted',
  'turn.blocked': 'The turn was blocked',
  'turn.maxTokens': 'The reply reached the output limit',
  'turn.error': 'Error: {message}',
  'tool.exit': 'exit {code}',
  'tool.signal': 'killed by {signal}',
  'tool.done': 'done',
  'tool.stopped': 'stopped',
  'tool.moreLines': '… {count} more lines',
  'tool.readLines': 'Read {count} of {total} lines',
  'tool.matches': '{count} matches in {files} files',
  'tool.paths': '{count} files',
  'tool.autoReview': 'Auto review rejected this action. Reason: {reason}',
  'tool.autoReviewNoReason': 'Auto review did not allow this action',
  'tool.imageBlock': '[image]',
  'tool.fileBlock': '[file {name}]',
  'session.started': 'New session {id} in {cwd}',
  'session.resumed': 'Resumed session {id} in {cwd}',
  'session.exit': 'Session {id} ends here. Resume it with: dsh terminal --resume {id}',
  'open.noContinue': 'No earlier session was found in {cwd}.',
  'open.noMatch': 'No session matches "{id}".',
  'open.ambiguous': 'More than one session starts with "{id}": {candidates}.',
  'error.promptFailed': 'The message was not sent: {message}',
  'error.commandFailed': 'The command failed: {message}',
  'command.unknown': 'There is no /{name} command. Type /help for the commands.',
  'command.unnamed': 'Command',
  'command.done': '  Done.',
  'command.failed': '  It did not run.',
  'error.notTty': 'dsh terminal needs an interactive terminal: run it from a shell, not with redirected input or output.',
  'error.connection': 'Lost the connection to the agent: {message}',
  'help.title': 'tBelt Code in the terminal',
  'help.send': 'Enter                 send the message',
  'help.newline': 'Alt+Enter, \\ Enter   add a line',
  'help.history': 'Up, Down             earlier messages (on the first and last line)',
  'help.edit': 'Ctrl+A, Ctrl+E       start and end of the line · Ctrl+W deletes a word · Ctrl+U clears the line',
  'help.cancel': 'Ctrl+C               stop the running turn; press it while idle to leave',
  'help.exit': 'Ctrl+D, /exit        leave',
  'help.sessions': '/sessions            choose another session',
  'help.rename': '/rename <title>      name this session',
  'help.model': '/model               choose the model',
  'help.new': '/new [directory]     start a session, in another directory if given',
  'help.attach': '/attach <file>       add a file or image to your next message · /detach removes them',
  'help.commands': '/help                this list; any other /command runs in the session',
  'image.marker': '[image {details}]',
  'attach.added': 'Attached {name}. It goes with your next message ({count} waiting).',
  'attach.cleared': 'Removed {count} attached files.',
  'attach.none': 'Nothing is attached.',
  'attach.usage': 'Usage: /attach <path to a file or image>',
  'attach.failed': 'Could not attach {path}: {message}',
  'attach.tooLarge': 'the file is larger than {limit}',
  'attach.notFile': 'it is not a file',
  'attach.pending': '{count} attached · /detach removes them',
  'age.now': 'just now',
  'age.minutes': '{count}m ago',
  'age.hours': '{count}h ago',
  'age.days': '{count}d ago',
  'picker.sessions': 'Choose a session',
  'picker.models': 'Choose a model',
  'picker.untitled': 'Untitled session',
  'picker.empty': 'Nothing matches.',
  'picker.keys': 'type to filter · ↑↓ move · Enter choose · Esc cancel',
  'picker.loadFailed': 'Could not load the list: {message}',
  'rename.usage': 'Usage: /rename <new title>',
  'rename.done': 'Session renamed to "{title}".',
  'rename.failed': 'Could not rename the session: {message}',
  'model.selected': 'Model for the next message: {model} ({provider}).',
  'model.failed': 'Could not select the model: {message}',
  'new.notDirectory': 'No directory at {path}.',
  'new.failed': 'Could not start a session: {message}',
  'switch.failed': 'Could not open that session: {message}',
} as const


/** Messages of the configuration screens: providers, web search, settings, plugins, agents and permissions. */
const CONFIG = {
  'prompt.keys': 'Enter confirm · Esc cancel',
  'picker.keysMulti': 'type to filter · ↑↓ move · Enter tick · pick the first row to continue · Esc cancel',
  'picker.done': 'Continue with {count} ticked',
  'picker.defaultModel': 'Choose the default model for new sessions',
  'question.heading': 'The agent has a question',
  'question.position': 'question {index} of {total}',
  'question.other': 'Type another answer…',
  'question.typeHint': 'Enter sends your answer · Esc goes back',
  'question.answered': '→ {answer}',
  'question.cancelled': 'You left the question unanswered.',
  'confirm.no': 'No, keep things as they are',
  'firstRun.noModel': 'No model is set up yet. Type /providers to add one.',
  'help.providers': '/providers           add a provider, set its API key and choose its models',
  'help.webSearch': '/web-search          choose the web search provider and its key',
  'help.settings': '/settings            edit agent, shell, subagent and other settings',
  'help.plugins': '/plugins             install, turn on or off and remove plugins',
  'help.agents': '/agents              see agent presets, including your Markdown agents',
  'help.permissions': '/permissions         choose how freely the agent may act',
  'help.modelDefault': '/model default       choose the model new sessions start with',
  'screen.busy': 'Another screen is open. Finish it first.',
  'screen.failed': 'The screen stopped: {message}',
  'settings.title': 'Choose settings to edit',
  'settings.count': '{count} values',
  'settings.openDocument': 'Open the settings file in your editor',
  'settings.openDocumentDetail': 'for lists and records that cannot be edited here',
  'settings.documentOpened': 'Opened the settings file.',
  'settings.documentFailed': 'Could not open the settings file: {message}',
  'settings.readOnly': 'The settings are read-only in this installation, so nothing was changed.',
  'settings.conflict': 'The settings changed somewhere else since this screen read them. Open the screen again and repeat the change.',
  'settings.writeFailed': 'The change was not saved: {message}',
  'settings.unset': 'not set',
  'settings.reset': 'Reset to the default',
  'settings.valueHint': 'now {current} · default {fallback} · an empty answer resets it',
  'settings.notNumber': '"{value}" is not a number.',
  'settings.saved': 'Saved {path} = {value}.',
  'settings.resetDone': 'Reset {path} to its default.',
  'settings.secretSet': 'a key is stored',
  'settings.secretUnset': 'no key stored',
  'settings.secretField': 'Keys are not shown or edited here. Use /providers or /web-search.',
  'providers.title': 'Choose a provider',
  'providers.addLocal': 'Add a local or custom provider',
  'providers.addLocalDetail': 'Ollama, LM Studio, or any compatible server',
  'providers.status.ready': 'ready',
  'providers.status.readyNoKey': 'ready, no key needed',
  'providers.status.needsKey': 'needs an API key',
  'providers.status.notSetUp': 'not set up',
  'providers.status.error': 'problem: {message}',
  'providers.action.setup': 'Set up with an API key and choose models',
  'providers.action.keyless': 'Set up without an API key',
  'providers.action.models': 'Choose models again',
  'providers.action.replaceKey': 'Replace the API key',
  'providers.action.removeKey': 'Remove the stored API key',
  'providers.action.remove': 'Remove this provider',
  'providers.noActions': '{name} is set up by the installation and has no settings to change here.',
  'providers.keyPrompt': 'API key for {name}',
  'providers.keyHint': 'Pasted text is hidden. It is checked with the provider before anything is saved. Esc cancels.',
  'providers.keyBlank': 'The key is empty.',
  'providers.keyIllegal': 'The key has characters a key cannot hold. Paste the key alone, without quotes or NAME=.',
  'providers.checking': 'Checking the key with the provider…',
  'providers.keyRejected': 'The provider rejected this key.',
  'providers.keyQuota': 'The provider accepted the key but it has no credit left.',
  'providers.noModels': 'The provider listed no models for this key.',
  'providers.modelsTitle': 'Choose the models to add',
  'providers.nothingChosen': 'No model chosen, so nothing was saved.',
  'providers.cancelled': 'Cancelled. Nothing was saved.',
  'providers.typedModels': 'Model ids',
  'providers.typedModelsHint': 'The provider lists no models. Type the ids to add, separated by commas or spaces.',
  'providers.added': 'Added {name} with {count} model(s). Type /model to choose one for the next message.',
  'providers.modelsSaved': '{name} now offers {count} model(s).',
  'providers.keyNotStored': 'The key was not stored: {message}. Run /providers again to retry.',
  'providers.saveAnyway': 'The key could not be checked. Save it anyway?',
  'providers.saveAnywayYes': 'Yes, save the key',
  'providers.keyReplaced': 'Replaced the API key of {name}.',
  'providers.removeKeyAsk': 'Remove the stored API key of {name}?',
  'providers.removeKeyYes': 'Yes, remove the key',
  'providers.keyNotRemoved': 'The key was not removed: {message}',
  'providers.keyRemoved': 'Removed the API key of {name}.',
  'providers.removeAsk': 'Remove {name} from your settings?',
  'providers.removeYes': 'Yes, remove the provider',
  'providers.removed': 'Removed {name}.',
  'providers.customUnavailable': 'This installation cannot declare custom providers.',
  'providers.templateTitle': 'What kind of provider?',
  'providers.templateOther': 'Another server',
  'providers.templateOtherDetail': 'an OpenAI-compatible gateway or any server you run',
  'providers.routePrompt': 'Name for the provider',
  'providers.routeHint': 'Lowercase letters, digits and hyphens, starting with a letter. Esc cancels.',
  'providers.routeInvalid': 'Use lowercase letters, digits and single hyphens, starting with a letter.',
  'providers.routeTaken': 'A provider named {route} already exists.',
  'providers.namePrompt': 'Display name',
  'providers.nameHint': 'Shown in model lists. Leave it empty to use the name.',
  'providers.baseUrlPrompt': 'Base URL of the server',
  'providers.baseUrlHint': 'For example http://localhost:11434/v1',
  'providers.baseUrlInvalid': 'The address must start with http:// or https://.',
  'providers.cleartext': 'This address is plain HTTP on another machine, so the key travels unencrypted.',
  'providers.protocolTitle': 'Which protocol does the server speak?',
  'providers.customKeyPrompt': 'API key, if the server wants one',
  'providers.customKeyHint': 'Leave it empty for none. Some local servers accept any text. Pasted text is hidden.',
  'webSearch.title': 'Choose the web search provider',
  'webSearch.automatic': 'Automatic',
  'webSearch.automaticDetail': 'let the service pick one that has a key',
  'webSearch.keySet': 'key stored',
  'webSearch.noKey': 'no key',
  'webSearch.unavailable': 'Web search settings are not available in this installation.',
  'webSearch.replaceAsk': 'A key for {provider} is stored. Replace it?',
  'webSearch.replaceYes': 'Yes, replace the key',
  'webSearch.keyPrompt': 'API key for {provider} search',
  'webSearch.checkFailed': 'The key could not be checked: {message}',
  'webSearch.saved': 'Web search now uses {provider}.',
  'plugins.title': 'Plugins',
  'plugins.install': 'Install a plugin bundle',
  'plugins.installDetail': 'from npm, a folder, a git address or a tarball',
  'plugins.single': 'Single plugins',
  'plugins.singleDetail': 'turn one running plugin on or off',
  'plugins.singleTitle': 'Choose a plugin',
  'plugins.status.on': 'on',
  'plugins.status.off': 'off',
  'plugins.status.installed': 'installed',
  'plugins.status.supplied': 'supplied by dsh',
  'plugins.status.optional': 'optional',
  'plugins.status.readOnly': 'fixed',
  'plugins.status.error': 'problem: {code}',
  'plugins.turnOn': 'Turn on',
  'plugins.turnOff': 'Turn off',
  'plugins.remove': 'Remove',
  'plugins.turnedOn': 'Turned on {name}.',
  'plugins.turnedOff': 'Turned off {name}.',
  'plugins.removeAsk': 'Remove {name}?',
  'plugins.removeYes': 'Yes, remove it',
  'plugins.removed': 'Removed {name}.',
  'plugins.readOnly': '{name} cannot be changed from here.',
  'plugins.specPrompt': 'Package to install',
  'plugins.specHint': 'A package name, a folder path, a git address or a tarball URL. Esc cancels.',
  'plugins.inspectFailed': 'Could not look at the package: {message}',
  'plugins.refused': 'The package cannot be installed: {reason}',
  'plugins.notBundle': '{name} is not a plugin bundle.',
  'plugins.installAsk': 'Install {name}?',
  'plugins.installYes': 'Yes, install it',
  'plugins.installing': 'Installing {name}. This can take a minute…',
  'plugins.installed': 'Installed {name}.',
  'plugins.restart': 'Saved {target}. Restart dsh to apply it.',
  'plugins.failed': 'Could not change {target}: {reason}',
  'plugins.pendingBuilds': 'These packages want to run build scripts and need approval first: {packages}',
  'agents.title': 'Choose an agent preset',
  'agents.hint': 'Your own agents are Markdown files in ~/.dsh/presets; each file becomes a preset.',
  'agents.none': 'This installation has no agent presets.',
  'agents.broken': 'cannot start: {reason}',
  'agents.action.session': 'Use for this session',
  'agents.action.default': 'Use for new sessions',
  'agents.action.show': 'Show its definition',
  'agents.selected': 'This session now runs the {name} preset.',
  'agents.locked': 'This session has already started, so its preset is fixed. Start a new one with /new.',
  'agents.selectFailed': 'Could not select the preset: {message}',
  'agents.defaultSet': 'New sessions will start with the {name} preset.',
  'agents.readFailed': 'Could not read the preset: {message}',
  'permissions.title': 'Choose a permission mode (* = default for new sessions)',
  'permissions.fullAccessAsk': 'Full access lets the agent change files anywhere and run commands without the sandbox. Allow it?',
  'permissions.fullAccessYes': 'Yes, allow full access',
  'permissions.scope.session': 'This session only',
  'permissions.scope.both': 'This session and new sessions',
  'permissions.session': 'This session now runs in {name} mode.',
  'permissions.default': 'New sessions will start in {name} mode.',
  'permissions.noCommand': 'This installation has no /permission command, so the mode was not changed.',
  'permissions.failed': 'Could not change the permission mode: {message}',
  'model.none': 'No model is available yet. Type /providers to add one.',
  'model.defaultSet': 'New sessions will start with {model} ({provider}).',
} as const

const COPY = { ...TOOL_TITLES, ...NEEDS, ...CHOICES, ...APPROVAL, ...TERMINAL, ...CONFIG, ...PANEL_COPY } as const

/** Key of any message the terminal client shows. */
export type CopyKey = keyof typeof COPY

/** Values substituted for `{name}` placeholders. */
export type CopyParams = Readonly<Record<string, string | number>>

/**
 * Look up a message and fill its placeholders.
 * @param key - message key; shared presenter keys are accepted through {@link copyKey}.
 * @param params - values for the `{name}` placeholders in the message.
 * @returns the English text; a placeholder without a value stays visible so the gap is noticed.
 */
export function t(key: CopyKey, params: CopyParams = {}): string {
  return COPY[key].replace(/\{(\w+)\}/gu, (placeholder, name: string) => {
    const value = params[name]
    return value === undefined ? placeholder : String(value)
  })
}

/**
 * Narrow a locale key returned by a shared presenter.
 * @param key - presenter key such as a tool title or an approval sentence.
 * @returns the same key when this dictionary holds it.
 * @throws when the presenters grew a key this dictionary lacks, which the type check catches first.
 */
export function copyKey(key: ToolTitleKey | ApprovalNeedKey | ApprovalChoiceKey): CopyKey {
  if (!(key in COPY)) throw new Error(`terminal copy lacks the key "${key}"`)
  return key
}
