/**
 * Messages of the panels that act on a session's work: the queue, files,
 * skills, subagents, jobs, schedule, goal, turns, workspaces and commands.
 * @module @deepseek-ai/dsh-terminal-views/copy-panels
 */

/** Queued messages. */
const QUEUE = {
  'queue.title': 'Queued messages',
  'queue.empty': 'No messages are waiting.',
  'queue.status': '{count} queued · /queue edits them',
  'queue.attached': '{count} attached',
  'queue.attachmentOnly': 'attachment only',
  'queue.action.edit': 'Edit the text',
  'queue.action.steer': 'Send it now, into the running turn',
  'queue.action.remove': 'Remove it',
  'queue.editPrompt': 'Queued message',
  'queue.editHint': 'Enter saves. Esc keeps the message as it is.',
  'queue.edited': 'Updated the queued message.',
  'queue.removed': 'Removed the queued message.',
  'queue.steered': 'Sent the message into the running turn.',
  'queue.failed': 'The message may have started already: {message}',
} as const

/** Files, references and skills. */
const FILES = {
  'attach.uploadFailed': 'Could not upload {name}: {message}',
  'reference.title': 'Reference',
  'reference.file': 'file',
  'reference.directory': 'directory',
  'reference.session': 'session',
  'reference.none': 'Nothing matches @{query}.',
  'reference.failed': 'Could not list references: {message}',
  'reference.unsafe': 'That name cannot be written as a reference.',
  'skills.title': 'Skills',
  'skills.empty': 'No skills are installed.',
  'skills.argsPrompt': 'Arguments for /{name}',
  'skills.argsHint': 'Enter runs the skill. Leave it empty to run it with no arguments.',
  'skills.failed': 'Could not list skills: {message}',
  'skills.runFailed': 'Could not run /{name}: {message}',
} as const

/** Subagents and jobs. */
const WORK = {
  'subagent.title': 'Subagents',
  'subagent.empty': 'This session has not started a subagent.',
  'subagent.mode.one-shot': 'one task',
  'subagent.mode.continuable': 'can be continued',
  'subagent.mode.unknown': 'unknown',
  'subagent.action.open': 'Open its conversation',
  'subagent.action.send': 'Send it a message',
  'subagent.action.interrupt': 'Interrupt it',
  'subagent.messagePrompt': 'Message for the subagent',
  'subagent.messageHint': 'Enter sends. It joins the subagent\'s queue.',
  'subagent.sent': 'Sent the message to the subagent.',
  'subagent.interrupted': 'Asked the subagent to stop.',
  'subagent.failed': 'The subagent did not accept it: {message}',
  'jobs.title': 'Background jobs',
  'jobs.empty': 'No background jobs.',
  'jobs.status.running': 'running',
  'jobs.status.stopping': 'stopping',
  'jobs.status.completed': 'completed',
  'jobs.status.killed': 'killed',
  'jobs.status.failed': 'failed',
  'jobs.action.output': 'Show its output',
  'jobs.action.kill': 'Stop it',
  'jobs.noOutput': 'No output yet.',
  'jobs.gap': '… output before this was dropped',
  'jobs.earlier': '… {count} earlier lines',
  'jobs.streaming': 'Still running. Open the job again for more.',
  'jobs.observeFailed': 'Could not follow the job: {message}',
  'jobs.killRequested': 'Asked the job to stop.',
  'jobs.alreadyFinished': 'The job had already finished.',
  'jobs.killFailed': 'Could not stop the job: {message}',
} as const

/** Scheduled follow-ups and the goal. */
const PLANNED = {
  'schedule.title': 'Scheduled follow-ups',
  'schedule.empty': 'Nothing is scheduled.',
  'schedule.once': 'once',
  'schedule.every': 'every {duration}',
  'schedule.daily': 'daily at {time}',
  'schedule.weekly': 'weekly at {time}',
  'schedule.cron': 'cron {expression}',
  'schedule.next': 'next {when}',
  'schedule.inactive': 'inactive',
  'schedule.action.history': 'Show when it ran',
  'schedule.action.title': 'Change the title',
  'schedule.action.prompt': 'Change the message',
  'schedule.action.timing': 'Change the timing',
  'schedule.action.delete': 'Delete it',
  'schedule.timing.at': 'Run once at a date and time',
  'schedule.timing.every': 'Repeat every number of seconds',
  'schedule.timing.daily': 'Run every day at a time',
  'schedule.timing.cron': 'Run on a cron schedule',
  'schedule.askTitle': 'Title',
  'schedule.askPrompt': 'Message the agent receives',
  'schedule.askAt': 'Date and time, such as 2026-12-01 09:00',
  'schedule.askEvery': 'Seconds between runs',
  'schedule.askDaily': 'Time of day, as HH:MM',
  'schedule.askCron': 'Cron expression with five fields',
  'schedule.badAt': 'Use a date and time such as 2026-12-01 09:00.',
  'schedule.badEvery': 'Use a whole number of seconds above zero.',
  'schedule.badDaily': 'Use HH:MM on a 24-hour clock.',
  'schedule.badCron': 'Use five fields, such as 0 9 * * 1.',
  'schedule.noHistory': 'It has not run yet.',
  'schedule.updated': 'Saved.',
  'schedule.conflict': 'It changed since the list was read. Open /schedule again.',
  'schedule.deleteAsk': 'Delete "{title}"?',
  'schedule.deleteYes': 'Delete it',
  'schedule.deleted': 'Deleted.',
  'schedule.failed': 'Could not change the follow-up: {message}',
  'schedule.listFailed': 'Could not list follow-ups: {message}',
  'goal.none': 'This session has no goal.',
  'goal.create': 'Set a goal',
  'goal.objectivePrompt': 'Goal',
  'goal.objectiveHint': 'What the agent should keep working toward. Enter saves.',
  'goal.phase.active': 'active',
  'goal.phase.paused': 'paused',
  'goal.phase.blocked': 'blocked',
  'goal.phase.complete': 'complete',
  'goal.rounds': 'round {started} of {max}',
  'goal.disarmed': 'not armed',
  'goal.action.edit': 'Change the goal',
  'goal.action.pause': 'Pause it',
  'goal.action.resume': 'Resume it',
  'goal.action.complete': 'Mark it complete',
  'goal.action.clear': 'Clear it',
  'goal.cleared': 'Cleared the goal.',
  'goal.saved': 'Saved the goal.',
  'goal.failed': 'Could not change the goal: {message}',
} as const

/** Turns, deliverables, workflows and feedback. */
const TURNS = {
  'deliverables.none': 'No turn has changed or presented files yet.',
  'deliverables.title': 'Files by turn',
  'deliverables.turn': 'Turn {turn}',
  'deliverables.changed': 'Changed, {count}',
  'deliverables.delivered': 'Presented, {count}',
  'deliverables.presented': 'Presented',
  'deliverables.summary': 'Files changed: {count} · /deliverables lists them',
  'trajectory.title': 'Turns',
  'trajectory.empty': 'No turns yet.',
  'trajectory.totals': '{turns} turns · {steps} steps · model {model} · tools {tools}',
  'trajectory.noPrompt': 'no prompt',
  'trajectory.notLoaded': 'not loaded',
  'trajectory.user': 'you: {text}',
  'trajectory.assistant': 'reply: {text}',
  'trajectory.call': 'call {name}',
  'trajectory.result': 'result {name}',
  'trajectory.resultFailed': 'failed {name}',
  'trajectory.end': 'end {reason}',
  'trajectory.turnNotLoaded': 'The events of that turn are not loaded. Scroll the history of the session in the GUI to load them.',
  'workflow.start': 'Workflow {name}',
  'workflow.phase': 'Phase {phase}',
  'workflow.agentStart': '{label} started',
  'workflow.agentEnd': '{label} {outcome}',
  'workflow.agentUnnamed': 'agent',
  'workflow.unnamed': 'run',
  'workflow.end': 'Workflow {name} {outcome}',
  'workflow.completed': 'completed',
  'workflow.cancelled': 'cancelled',
  'workflow.failed': 'failed',
  'workflow.stopped': 'stopped',
  'feedback.title': 'Feedback',
  'feedback.rate': 'Rate the last reply',
  'feedback.send': 'Send feedback about this session',
  'feedback.positive': 'Good reply',
  'feedback.negative': 'Poor reply',
  'feedback.remove': 'Remove my rating',
  'feedback.noReply': 'There is no reply to rate yet.',
  'feedback.notePrompt': 'Note, optional',
  'feedback.noteHint': 'Enter saves the rating. Leave it empty to rate without a note.',
  'feedback.textPrompt': 'Feedback',
  'feedback.textHint': 'Enter sends it.',
  'feedback.rated': 'Saved your rating.',
  'feedback.removed': 'Removed your rating.',
  'feedback.sent': 'Sent the feedback.',
  'feedback.failed': 'Could not save the feedback: {message}',
} as const

/** Sessions, workspaces, worktrees and files outside the terminal. */
const PLACES = {
  'fork.title': 'Fork at',
  'fork.now': 'The end of the conversation',
  'fork.turn': 'After turn {turn}: {text}',
  'fork.opened': 'Forked. Opening the copy.',
  'fork.failed': 'Could not fork the session: {message}',
  'organize.title': 'Sessions',
  'organize.archive': 'Archive it',
  'organize.unarchive': 'Bring it back from the archive',
  'organize.pin': 'Pin it',
  'organize.unpin': 'Unpin it',
  'organize.archived': 'Archived.',
  'organize.unarchived': 'Brought back.',
  'organize.pinned': 'Pinned.',
  'organize.unpinned': 'Unpinned.',
  'organize.stopAsk': 'This session is working. Stop its work and archive it?',
  'organize.stopYes': 'Stop and archive',
  'organize.failed': 'Could not change the session: {message}',
  'status.untitled': 'Untitled session',
  'status.id': 'Session',
  'status.directory': 'Directory',
  'status.activity': 'State',
  'status.activityWorking': 'working',
  'status.activityIdle': 'idle',
  'status.model': 'Model',
  'status.permissions': 'Permissions',
  'status.plan': 'Plan mode',
  'status.on': 'on',
  'status.off': 'off',
  'status.goal': 'Goal',
  'status.queue': 'Queued',
  'status.turns': 'Turns',
  'status.turnsValue': '{turns} turns · {steps} steps · model {model} · tools {tools}',
  'status.tokens': 'Tokens',
  'status.tokensValue': 'input {input} · cached {cached} · output {output}',
  'status.context': 'Context',
  'status.contextValue': '{used} of {window} tokens · {percent}%',
  'workspace.title': 'Workspaces',
  'workspace.empty': 'No workspace is registered.',
  'workspace.sessions': '{count} sessions',
  'workspace.add': 'Add a workspace',
  'workspace.addPrompt': 'Directory of the workspace',
  'workspace.addHint': 'Enter adds it. ~ and relative paths work.',
  'workspace.notDirectory': '{path} is not a directory.',
  'workspace.action.rename': 'Rename it',
  'workspace.action.remove': 'Remove it',
  'workspace.renamePrompt': 'New title',
  'workspace.removeAsk': 'Remove "{title}" from the list? Its files stay where they are.',
  'workspace.removeYes': 'Remove it',
  'workspace.added': 'Added {title}.',
  'workspace.renamed': 'Renamed.',
  'workspace.removed': 'Removed.',
  'workspace.failed': 'Could not change the workspace: {message}',
  'worktrees.title': 'Worktrees',
  'worktrees.create': 'Create a worktree',
  'worktrees.detached': 'detached',
  'worktrees.primary': 'main checkout',
  'worktrees.locked': 'locked',
  'worktrees.prunable': 'missing on disk',
  'worktrees.linked': 'A worktree of the repository.',
  'worktrees.notLinked': 'Not a linked worktree.',
  'worktrees.clean': 'No uncommitted changes.',
  'worktrees.uncommitted': 'Uncommitted changes, {count}',
  'worktrees.namePrompt': 'Name of the branch, optional',
  'worktrees.nameHint': 'Enter creates it. Leave it empty to let the Host name it.',
  'worktrees.created': 'Created worktree on {branch}, from {base}.',
  'worktrees.warning': 'Warning: {text}',
  'worktrees.action.open': 'Start a session in it',
  'worktrees.action.inspect': 'Show its state',
  'worktrees.action.remove': 'Remove it',
  'worktrees.removeAsk': 'Remove the worktree{branch}?',
  'worktrees.removeYes': 'Remove it',
  'worktrees.removeForceAsk': 'It has uncommitted changes. Remove it anyway?',
  'worktrees.removeForceYes': 'Remove it and lose the changes',
  'worktrees.removed': 'Removed the worktree.',
  'worktrees.branchDeleted': 'Deleted its branch.',
  'worktrees.noWorkspace': 'This directory is not in a registered workspace. Add it with /workspaces.',
  'worktrees.failed': 'Could not change the worktree: {message}',
  'open.title': 'Open with',
  'open.unavailable': 'This host cannot open applications.',
  'open.none': 'No application was found for this directory.',
  'open.default': 'default',
  'open.reveal': 'Show in the file manager',
  'open.opened': 'Opened {path}.',
  'open.failed': 'Could not open it: {message}',
  'budget.of': '{spent} of {limit}',
  'budget.session': 'This session: {spend}',
  'budget.month': 'Month {month}: {spend}',
  'budget.unpriced': 'Model calls with no known price are not counted: {session} this session, {month} this month.',
  'budget.hint': '/budget <usd> sets this session\'s limit. /budget month <usd> sets the monthly limit. off clears one.',
  'budget.failed': 'Could not read the budget: {message}',
  'plan.none': 'The agent has not submitted a plan in the loaded history.',
  'commands.title': 'Commands',
  'commands.empty': 'The Host offers no commands.',
  'commands.failed': 'Could not list commands: {message}',
} as const

/** Help lines of the panels. */
const PANEL_HELP = {
  'help.queue': '/queue               edit, send now or remove queued messages',
  'help.reference': 'Tab after @          complete a file, directory or session name',
  'help.deliverables': '/deliverables        files each turn changed or presented',
  'help.trajectory': '/trajectory          turns with timing, and the events of one turn',
  'help.skills': '/skills              list skills and run one',
  'help.subagents': '/subagents           open, message or interrupt subagents',
  'help.jobs': '/jobs                background jobs: output and stop',
  'help.schedule': '/schedule            scheduled follow-ups',
  'help.goal': '/goal                show and manage the goal · /goal <text> sets it',
  'help.feedback': '/feedback            rate the last reply or send feedback',
  'help.fork': '/fork                copy this session up to a turn',
  'help.organize': '/organize            archive or pin sessions',
  'help.status': '/status              model, permissions, turns, tokens and context',
  'help.workspaces': '/workspaces          add, rename or remove workspaces',
  'help.worktrees': '/worktrees           create, inspect or remove git worktrees',
  'help.open': '/open [path]          open this directory or a path in an application',
  'help.budget': '/budget              spend against the limits · /budget <usd> sets one',
  'help.plan': '/plan show            print the newest plan · /plan toggles plan mode',
  'help.commandsList': '/commands            every command, including those of plugins',
} as const

/** All panel messages. */
export const PANEL_COPY = { ...QUEUE, ...FILES, ...WORK, ...PLANNED, ...TURNS, ...PLACES, ...PANEL_HELP } as const
