/** Generate the shared-instance package graph from workspace peer dependencies. */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  collectPackageGraph,
  escapeMermaidLabel as escLabel,
  graphNodeId as nodeId,
  type PackageGraphNode,
} from './package-graph.ts'

const root = resolve(import.meta.dirname, '..')
const SOURCE = 'docs/module-graph.md'
type Pkg = PackageGraphNode

const GROUP_ORDER = [
  'util',
  'llm',
  'core',
  'goal',
  'bash',
  'fs',
  'skill',
  'compact',
  'subagent',
  'web',
  'spill',
  'timeout',
  'todo',
  'plan',
  'cordis',
  'hooks',
  'session-persistence',
  'session-query',
  'session-title',
  'support',
  'acp',
  'ui',
]

function packageLink(pkg: Pkg): string {
  return `[\`${pkg.short}\`](../${pkg.rel})`
}

/**
 * Render the complete deterministic package graph.
 * @param pkgs - Dependency-first package nodes.
 * @returns Complete generated Markdown.
 */
export function renderModuleGraph(pkgs: readonly Pkg[]): string {
  const edges: string[] = []
  for (const pkg of pkgs) {
    for (const dependency of pkg.deps) edges.push(`  ${nodeId('pkg', pkg.short)} --> ${nodeId('pkg', dependency)}`)
  }
  const byShort = new Map(pkgs.map(pkg => [pkg.short, pkg]))
  const groups = [...new Set(pkgs.map(pkg => pkg.group))].sort((left, right) => {
    const leftIndex = GROUP_ORDER.indexOf(left)
    const rightIndex = GROUP_ORDER.indexOf(right)
    const normalizedLeft = leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex
    const normalizedRight = rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex
    return normalizedLeft - normalizedRight || left.localeCompare(right)
  })
  const groupBlocks: string[] = []
  for (const group of groups) {
    groupBlocks.push(`  subgraph ${nodeId('group', group)}["packages/${escLabel(group)}"]`)
    for (const pkg of pkgs.filter(candidate => candidate.group === group)
      .sort((left, right) => left.short.localeCompare(right.short))) {
      groupBlocks.push(`    ${nodeId('pkg', pkg.short)}["${escLabel(pkg.short)}"]`)
    }
    groupBlocks.push('  end')
  }
  const rows = pkgs.map((pkg) => {
    const dependencies = pkg.deps.length > 0
      ? pkg.deps.map((dependency) => {
        const target = byShort.get(dependency)
        return target ? packageLink(target) : `\`${dependency}\``
      }).join(', ')
      : '—'
    return `| ${packageLink(pkg)} | \`${pkg.group}\` | ${dependencies} |`
  })
  return [
    '<!-- Generated by scripts/gen-module-graph.ts — do not edit by hand.\n     Run `pnpm run gen-module-graph` to regenerate. -->',
    '',
    '# Shared-instance dependency graph',
    '',
    'Peer dependencies among the `@deepseek-ai/dsh-*` harness packages. A peer means the consumer requires a shared instance; ordinary runtime dependencies and development-only relationships are not shown. The graph is grouped by the `packages/<group>/<pkg>` hierarchy. An edge `a --> b` means package `a` has package `b` as a peer. Names omit the `@deepseek-ai/dsh-` prefix.',
    '',
    '```mermaid',
    'flowchart TD',
    ...groupBlocks,
    ...edges,
    '```',
    '',
    '| Package | Group | Peer dependencies |',
    '| --- | --- | --- |',
    ...rows,
    '',
  ].join('\n')
}

/**
 * Compute the graph document from the current workspace manifests.
 * @param scanRoot - Repository root containing packages and documentation.
 * @returns Exact generated Markdown.
 */
export function computeModuleGraphOutput(scanRoot: string = root): string {
  const packages = collectPackageGraph(scanRoot, GROUP_ORDER, 'gen-module-graph')
  return renderModuleGraph(packages)
}

/**
 * Write the graph document.
 * @param scanRoot - Repository root containing packages and documentation.
 * @returns Repository-relative paths whose content changed.
 */
export function writeModuleGraph(scanRoot: string = root): string[] {
  const content = computeModuleGraphOutput(scanRoot)
  const destination = resolve(scanRoot, SOURCE)
  if (existsSync(destination) && readFileSync(destination, 'utf8') === content) return []
  writeFileSync(destination, content)
  return [SOURCE]
}

/** CLI entry: regenerate by default, or verify the output with `--check`. @returns Nothing. */
export function main(): void {
  const expected = computeModuleGraphOutput(root)
  if (process.argv.includes('--check')) {
    const destination = resolve(root, SOURCE)
    const stale = !existsSync(destination) || readFileSync(destination, 'utf8') !== expected
    if (!stale) {
      console.log('gen-module-graph: docs/module-graph.md is up to date.')
      return
    }
    console.error(`gen-module-graph: stale — ${SOURCE}. Run \`pnpm run gen-module-graph\` and commit the result.`)
    process.exitCode = 1
    return
  }
  const changed = writeModuleGraph(root)
  console.log(`gen-module-graph: docs/module-graph.md computed, ${String(changed.length)} written.`)
}

if (process.argv[1] !== undefined && import.meta.filename === resolve(process.argv[1])) main()
